/**
 * Автозаполнение сметы по типу объекта: ссылки на позиции прайса по стабильному fillKey
 * (ключ задаётся при сидировании БД и совпадает с полем fillKey у позиции).
 */

export interface AutoFillProfile {
  label: string;
  cablePerSqm: number;
  cableDistribution: { fillKey: string; share: number }[];
  extras: { fillKey: string; perSqm: number }[];
}

export const AUTO_FILL_PROFILES: AutoFillProfile[] = [
  {
    label: "Квартира / Апартаменты",
    cablePerSqm: 3.5,
    cableDistribution: [
      { fillKey: "cable_3x2_5", share: 0.5 },
      { fillKey: "cable_3x6", share: 0.18 },
      { fillKey: "utp_sat_tel", share: 0.15 },
      { fillKey: "cable_5x6", share: 0.07 },
      { fillKey: "cable_acoustic", share: 0.05 },
      { fillKey: "cable_decor", share: 0.05 },
    ],
    extras: [
      { fillKey: "pipe_pvh_16_25", perSqm: 3.0 },
      { fillKey: "pull_corrugated_with", perSqm: 3.0 },
      { fillKey: "chase_brick", perSqm: 1.8 },
      { fillKey: "plaster_chase", perSqm: 1.8 },
      { fillKey: "socket_box_in_wall", perSqm: 0.55 },
      { fillKey: "hole_drill_brick_75", perSqm: 0.55 },
      { fillKey: "socket_inner_zk", perSqm: 0.45 },
      { fillKey: "switch_1_inner", perSqm: 0.12 },
      { fillKey: "spot_light_ceiling", perSqm: 0.3 },
      { fillKey: "hole_spot_fixture", perSqm: 0.3 },
      { fillKey: "junction_box_install", perSqm: 0.15 },
      { fillKey: "junction_wago_group", perSqm: 0.45 },
      { fillKey: "din_automation_module", perSqm: 0.55 },
      { fillKey: "panel_cable_entry", perSqm: 0.55 },
      { fillKey: "drill_through_brick", perSqm: 0.08 },
      { fillKey: "lug_nshvi", perSqm: 0.55 },
    ],
  },
  {
    label: "Частный дом",
    cablePerSqm: 4.0,
    cableDistribution: [
      { fillKey: "cable_3x2_5", share: 0.42 },
      { fillKey: "cable_3x6", share: 0.18 },
      { fillKey: "utp_sat_tel", share: 0.15 },
      { fillKey: "cable_5x6", share: 0.1 },
      { fillKey: "cable_5x10", share: 0.05 },
      { fillKey: "cable_acoustic", share: 0.05 },
      { fillKey: "cable_decor", share: 0.05 },
    ],
    extras: [
      { fillKey: "pipe_pvh_16_25", perSqm: 3.4 },
      { fillKey: "pull_corrugated_with", perSqm: 3.4 },
      { fillKey: "chase_brick", perSqm: 2.0 },
      { fillKey: "plaster_chase", perSqm: 2.0 },
      { fillKey: "socket_box_in_wall", perSqm: 0.55 },
      { fillKey: "hole_drill_brick_75", perSqm: 0.55 },
      { fillKey: "socket_inner_zk", perSqm: 0.45 },
      { fillKey: "switch_1_inner", perSqm: 0.12 },
      { fillKey: "spot_light_ceiling", perSqm: 0.28 },
      { fillKey: "hole_spot_fixture", perSqm: 0.28 },
      { fillKey: "junction_box_install", perSqm: 0.15 },
      { fillKey: "junction_wago_group", perSqm: 0.5 },
      { fillKey: "din_automation_module", perSqm: 0.6 },
      { fillKey: "panel_cable_entry", perSqm: 0.6 },
      { fillKey: "drill_through_brick", perSqm: 0.1 },
      { fillKey: "lug_nshvi", perSqm: 0.6 },
    ],
  },
  {
    label: "Офис / Административное здание",
    cablePerSqm: 6.5,
    cableDistribution: [
      { fillKey: "cable_3x2_5", share: 0.35 },
      { fillKey: "cable_3x6", share: 0.12 },
      { fillKey: "utp_sat_tel", share: 0.3 },
      { fillKey: "cable_5x6", share: 0.08 },
      { fillKey: "cable_3x10", share: 0.05 },
      { fillKey: "cable_5x10", share: 0.05 },
      { fillKey: "cable_acoustic", share: 0.05 },
    ],
    extras: [
      { fillKey: "cable_channel_25x16", perSqm: 1.2 },
      { fillKey: "cable_channel_60x40", perSqm: 0.6 },
      { fillKey: "tray_metal_100", perSqm: 0.25 },
      { fillKey: "socket_inner_zk", perSqm: 0.55 },
      { fillKey: "switch_1_inner", perSqm: 0.1 },
      { fillKey: "light_ars_armstrong", perSqm: 0.2 },
      { fillKey: "junction_box_install", perSqm: 0.12 },
      { fillKey: "junction_wago_group", perSqm: 0.55 },
      { fillKey: "din_automation_module", perSqm: 0.65 },
      { fillKey: "panel_cable_entry", perSqm: 0.65 },
      { fillKey: "rj45_crimp", perSqm: 0.3 },
      { fillKey: "lug_nshvi", perSqm: 0.65 },
      { fillKey: "drill_through_brick", perSqm: 0.06 },
    ],
  },
  {
    label: "Ресторан / Кафе / Общепит",
    cablePerSqm: 8.0,
    cableDistribution: [
      { fillKey: "cable_3x2_5", share: 0.3 },
      { fillKey: "cable_3x6", share: 0.18 },
      { fillKey: "cable_5x6", share: 0.15 },
      { fillKey: "utp_sat_tel", share: 0.12 },
      { fillKey: "cable_5x10", share: 0.1 },
      { fillKey: "cable_5x16", share: 0.05 },
      { fillKey: "cable_acoustic", share: 0.05 },
      { fillKey: "cable_decor", share: 0.05 },
    ],
    extras: [
      { fillKey: "pipe_pvh_16_25", perSqm: 4.5 },
      { fillKey: "pull_corrugated_with", perSqm: 4.5 },
      { fillKey: "tray_metal_200_400", perSqm: 0.3 },
      { fillKey: "tray_metal_500_600", perSqm: 0.15 },
      { fillKey: "socket_inner_zk", perSqm: 0.5 },
      { fillKey: "connector_1ph_flush", perSqm: 0.04 },
      { fillKey: "switch_1_inner", perSqm: 0.1 },
      { fillKey: "spot_light_ceiling", perSqm: 0.25 },
      { fillKey: "hole_spot_fixture", perSqm: 0.25 },
      { fillKey: "junction_box_install", perSqm: 0.14 },
      { fillKey: "junction_wago_group", perSqm: 0.5 },
      { fillKey: "din_automation_module", perSqm: 0.6 },
      { fillKey: "panel_cable_entry", perSqm: 0.6 },
      { fillKey: "drill_through_concrete", perSqm: 0.06 },
      { fillKey: "lug_nshvi", perSqm: 0.6 },
    ],
  },
  {
    label: "Торговый центр / Магазин",
    cablePerSqm: 8.0,
    cableDistribution: [
      { fillKey: "cable_3x2_5", share: 0.28 },
      { fillKey: "cable_3x6", share: 0.15 },
      { fillKey: "utp_sat_tel", share: 0.2 },
      { fillKey: "cable_5x6", share: 0.12 },
      { fillKey: "cable_5x10", share: 0.1 },
      { fillKey: "cable_5x16", share: 0.05 },
      { fillKey: "cable_3x10", share: 0.05 },
      { fillKey: "cable_acoustic", share: 0.05 },
    ],
    extras: [
      { fillKey: "tray_metal_200_400", perSqm: 0.4 },
      { fillKey: "tray_metal_500_600", perSqm: 0.2 },
      { fillKey: "tray_console", perSqm: 0.2 },
      { fillKey: "socket_outer_zk", perSqm: 0.35 },
      { fillKey: "socket_inner_zk", perSqm: 0.2 },
      { fillKey: "switch_1_inner", perSqm: 0.08 },
      { fillKey: "light_ars_armstrong", perSqm: 0.18 },
      { fillKey: "junction_box_install", perSqm: 0.1 },
      { fillKey: "junction_wago_group", perSqm: 0.45 },
      { fillKey: "din_automation_module", perSqm: 0.55 },
      { fillKey: "panel_cable_entry", perSqm: 0.55 },
      { fillKey: "drill_through_concrete", perSqm: 0.05 },
      { fillKey: "lug_nshvi", perSqm: 0.55 },
    ],
  },
  {
    label: "Производство / Склад / Цех",
    cablePerSqm: 4.5,
    cableDistribution: [
      { fillKey: "cable_3x2_5", share: 0.15 },
      { fillKey: "cable_3x6", share: 0.15 },
      { fillKey: "cable_5x6", share: 0.15 },
      { fillKey: "cable_5x10", share: 0.15 },
      { fillKey: "cable_5x16", share: 0.1 },
      { fillKey: "cable_5x35", share: 0.1 },
      { fillKey: "utp_sat_tel", share: 0.1 },
      { fillKey: "cable_3x10", share: 0.1 },
    ],
    extras: [
      { fillKey: "tray_metal_200_400", perSqm: 0.3 },
      { fillKey: "tray_metal_500_600", perSqm: 0.1 },
      { fillKey: "tray_console", perSqm: 0.2 },
      { fillKey: "socket_outer_zk", perSqm: 0.15 },
      { fillKey: "connector_3ph_surface", perSqm: 0.03 },
      { fillKey: "switch_1_outer", perSqm: 0.05 },
      { fillKey: "light_ceiling", perSqm: 0.08 },
      { fillKey: "junction_box_install", perSqm: 0.08 },
      { fillKey: "din_automation_module", perSqm: 0.4 },
      { fillKey: "panel_cable_entry", perSqm: 0.4 },
      { fillKey: "drill_metal", perSqm: 0.04 },
      { fillKey: "lug_nshvi", perSqm: 0.4 },
    ],
  },
  {
    label: "Гостиница",
    cablePerSqm: 5.5,
    cableDistribution: [
      { fillKey: "cable_3x2_5", share: 0.4 },
      { fillKey: "cable_3x6", share: 0.15 },
      { fillKey: "utp_sat_tel", share: 0.2 },
      { fillKey: "cable_5x6", share: 0.08 },
      { fillKey: "cable_acoustic", share: 0.07 },
      { fillKey: "cable_decor", share: 0.05 },
      { fillKey: "cable_3x10", share: 0.05 },
    ],
    extras: [
      { fillKey: "pipe_pvh_16_25", perSqm: 4.5 },
      { fillKey: "pull_corrugated_with", perSqm: 4.5 },
      { fillKey: "chase_brick", perSqm: 2.5 },
      { fillKey: "plaster_chase", perSqm: 2.5 },
      { fillKey: "socket_box_in_wall", perSqm: 0.6 },
      { fillKey: "hole_drill_brick_75", perSqm: 0.6 },
      { fillKey: "socket_inner_zk", perSqm: 0.5 },
      { fillKey: "switch_1_inner", perSqm: 0.15 },
      { fillKey: "switch_2_inner_pass", perSqm: 0.06 },
      { fillKey: "spot_light_ceiling", perSqm: 0.3 },
      { fillKey: "hole_spot_fixture", perSqm: 0.3 },
      { fillKey: "light_wall_bracket", perSqm: 0.1 },
      { fillKey: "junction_box_install", perSqm: 0.14 },
      { fillKey: "junction_wago_group", perSqm: 0.55 },
      { fillKey: "din_automation_module", perSqm: 0.65 },
      { fillKey: "panel_cable_entry", perSqm: 0.65 },
      { fillKey: "lug_nshvi", perSqm: 0.65 },
    ],
  },
];
